language: ruby

cache:
  bundler: true
  directories:
    - vendor/bundler

before_install:
  - make doctor
  - touch Gemfile  # ensure dependencies are checked

install:
  - make install

script:
  - make check
  - make test

notifications:
  email:
    on_success: never
    on_failure: change
